# Generated by Django 4.0.2 on 2022-02-15 13:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
