# Generated by Django 4.0.2 on 2022-02-27 07:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following',
            new_name='follows',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='followed',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user', 'follows')},
        ),
    ]
