# Generated by Django 4.0.2 on 2022-02-15 13:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_at_recipe_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
