# Generated by Django 4.0.2 on 2022-02-15 15:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipes/default.jpeg', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
