# Generated by Django 4.0.2 on 2022-03-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comment_rating_ingredient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'recipe')},
        ),
    ]
