# Generated by Django 4.0.2 on 2022-03-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ingredient_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default='[]'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
