# Generated by Django 4.0.2 on 2022-03-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_recipe_ingredients_delete_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=dict),
        ),
    ]
